Katnip/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('', include('users.urls')),
    path('', include('meow.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meow/urls.py
from django.urls import path

from meow import views

app_name = "meow"

urlpatterns = [
    path('', views.MeowIndexView.as_view(), name="index"),
    path('search/', views.MeowSearchView.as_view(), name="search"),
    path('h/', views.MeowHashView.as_view(), name="hash"),
    path('meow_post/', views.MeowCreateView.as_view(), name="create"),
    path('meow/<slug:slug>/', views.MeowDetailView.as_view(), name="detail"),
    path('meow/<slug:slug>/delete/', views.MeowDeleteView.as_view(), name="delete"),
]

users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path('login/', views.SiteLoginView.as_view(), name="login"),
    path('logout/', views.SiteLogoutView.as_view(), name="logout"),
    path('register/', views.SiteRegisterView.as_view(), name="register"),
    path('update/', views.ProfileUpdateView.as_view(), name="create"),
    path('u/<slug:slug>/', views.UserDetailView.as_view(), name="detail"),
]

meow/models.py
import random
import string
import re

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.utils.translation import gettext as _


class Meow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                            verbose_name=_("User"))
    parent = models.ForeignKey('self', on_delete=models.CASCADE,
                           null=True, blank=True,
                           verbose_name=_("Parent"))
    slug = models.SlugField(_("URL"), max_length=20,
                            null=True, blank=True)
    body = models.TextField(_("Body"), max_length=512)
    image = models.ImageField(_("Image"), upload_to="meow/%Y/%m/%d/",
                              null=True, blank=True)
    pub_time = models.DateTimeField(_("Publish Time"), auto_now_add=True)

    class Meta:
        verbose_name = "Meow"
        verbose_name_plural = _("Meows")
        ordering = ['-pub_time']


    def __str__(self):
        return "%s - %s" % (self.user, self.body[:20])

    def save(self, *args, **kwargs):
        if not self.slug:
            s = string.ascii_letters + string.digits
            while True:
                ran_slug =''.join(random.sample(s, 14))
                try:
                    is_slug = self.__class__.objects.get(slug=ran_slug)
                except Exception:
                    is_slug = None
                if not is_slug:
                    self.slug = ran_slug
                    break
                continue
            super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('meow:detail', args=[str(self.slug)])

    def get_body(self):
        raw = self.body
        safe = re.sub('<[^<]+?>', '', raw)
        with_mention = re.sub('@([a-z,A-Z,0-9]+)',
                              r'<a href="/u/\1">@\1</a>',
                              safe)
        with_hash = re.sub('\#([a-z,A-Z,0-9]+)',
                              r'<a href="/h/?q=\1">#\1</a>',
                              with_mention)
        with_url = re.sub(r'((http[s]?:\/\/)?[^\s(["<,>]*\.[^\s[",><]*)',
                              r'<a href="//\1" target="_blank">\1</a>',
                              with_hash)
        return with_url

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext as _


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                verbose_name=_("User"))
    avatar = models.ImageField(_("Avatar"), upload_to="avatars/",
                               null=True, blank=True)
    bio = models.CharField(_("User Bio"), max_length=512,
                           null=True, blank=True)

    class Meta:
        verbose_name = _("Profile")
        verbose_name_plural = _("Profiles")

meow/forms.py
from django import forms
from meow.models import Meow


class MeowForm(forms.ModelForm):
    class Meta:
        model = Meow
        fields = ['body', 'image']

users/forms.py
from django import forms
from users.models import Profile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar', 'bio']

meow/views.py
from django.db.models import Q
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.http.response import HttpResponseRedirect
from meow.models import Meow
from meow.forms import MeowForm


class MeowIndexView(ListView):
    model = Meow
    template_name = "meow_index.html"
    context_object_name = "meow_list"

    def get_queryset(self):
        return Meow.objects.all().order_by('-pub_time')


class MeowDetailView(DetailView):
    model = Meow
    slug_field = "slug"
    template_name = "meow_detail.html"
    context_object_name = "meow"


class MeowCreateView(CreateView):
    form_class = MeowForm
    template_name = "uder_form.html"
    success_url = "/"

    def post(self, request, *args, **kwargs):
        form = MeowForm(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
        return HttpResponseRedirect("/")


class MeowDeleteView(DeleteView):
    model = Meow
    success_url = "/"


class MeowSearchView(MeowIndexView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get("q")
        return context

    def get_queryset(self):
        q = self.request.GET.get("q")
        return Meow.objects.filter(
                Q(body__icontains=q) |
                Q(user__username=q)
            )


class MeowHashView(MeowIndexView):
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['q'] = self.request.GET.get("q")
        return context

    def get_queryset(self):
        q = "#" + self.request.GET.get("q")
        return Meow.objects.filter(body__icontains=q)

users/views.py
from django.views.generic import DetailView, CreateView, UpdateView, FormView
from django.contrib.auth import views as auth_views
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.http.response import HttpResponseRedirect
from django.utils.translation import gettext as _
from users.forms import ProfileForm


class UserDetailView(DetailView):
    model = User
    slug_field = "username"
    template_name = "user.html"
    context_object_name = "user"


class SiteLoginView(auth_views.LoginView):
    template_name = "user_form.html"

    def get_success_url(self):
        return "/"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['button'] = _("Login")
        return context
    

class SiteLogoutView(auth_views.LogoutView):
    next_page = "/"


class SiteRegisterView(CreateView):
    template_name = "user_form.html"
    success_url = "/login/"
    form_class = UserCreationForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile_form'] = ProfileForm()
        context['button'] = _("Register")
        return context

    def post(self, request, *args, **kwargs):
        form = UserCreationForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        if form.is_valid() and profile_form.is_valid():
            new_user = form.save()
            new_profile = profile_form.save(commit=False)
            new_profile.user = new_user
            new_profile.save()
            return HttpResponseRedirect("/login/")
        else:
            self.object = None
            cnt = self.get_context_data()
            return render(request, self.template_name, cnt)



class ProfileUpdateView(UpdateView):
    template_name = "user_form.html"
    success_url = "/"
    form_class = ProfileForm

    def get_object(self):
        return self.request.user.profile

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['button'] = _("Update")
        return context

templates/base.html
{% load static %}

<!doctype html>
<html lang="tr">
	<head>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<title>Meow {% block title %}{% endblock title %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
	</head>
	<body>
        <header>
        {% include "partials/nav.html" %}
        </header>
        <div class="container">
            <div class="row">
                {% include "partials/sidebar.html" %}
                <div class="col-md-9 main">
                    {% block body %}
                    {% endblock body %}
                </div>
            </div>
        </div>
		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
        <script>
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            })
        </script>
	</body>
</html>

templates/meow/meow_confirm_delete.html
{% extends "base.html" %}

{% block title %} - Silmeyi Onayla {% endblock title %}

{% block body %}
{% if meow.user == user %}
<form method="post">
    {% csrf_token %}
    <p>Bu <b>Meow'ı</b> silmek istediğinize emin misiniz?</p>
    <input type="submit" value="Onayla">
</form>
{% endif %}
{% endblock body %}

templates/meow_detail.html
{% extends "base.html" %}

{% load thumbnail %}

{% block title %}- {{ meow.body|truncatechars:9 }} {% endblock title %}

{% block body %}
    {% include "partials/meow.html" with meow=meow %}
{% endblock body %}

templates/meow_index.html
{% extends "base.html" %}

{% load thumbnail %}

{% block body %}
	{% for meow in meow_list %}
        {% include  "partials/meow.html" with meow=meow %}
	{% endfor %}
{% endblock body %}

templates/partials/meow.html
{% load thumbnail %}

<div class="media meow">
    {% thumbnail meow.user.profile.avatar "64x64" format="PNG" as im %}
        <img src="{{ im.url }}" class="align-self-start mr-3" alt="...">
    {% endthumbnail %}
    <div class="media-body">
        <h5 class="mt-0">
            <a href="/u/{{ meow.user.get_username }}">
                {{ meow.user.get_username }}
            </a>
        </h5>
        <small>
            <a href="{{ meow.get_absolute_url }}">
                {{ meow.pub_time }}
            </a>
            {% if meow.user == user %}
             | <a class="del-meow" href="{% url 'meow:delete' meow.slug %}">
                 <span class="badge badge-danger" data-toggle="tooltip" title="Bu Meow'ı Sil">
                     X
                 </span>
                 </a>
            {% endif %}
        </small>
        <p>{{ meow.get_body|safe }}</p>
        {% if meow.image %}
            {% thumbnail meow.image "400" as im %}
            <a href="{{ meow.image.url }}" target="_blank">
                <img class="img-fluid" src="{{ im.url }}">
            </a>
            {% endthumbnail %}
        {% endif %}
    </div>
</div>

templates/partials/nav.html
<nav class="navbar container navbar-expand-lg fixed-top navbar-dark bg-dark">
  <a class="navbar-brand mb-0 h1" href="/">KatNip</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Anasayfa<span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:logout' %}">Çıkış Yap</a>
      </li>
      {% else %}
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:login' %}">Giriş Yap</a>
      </li>
      <li class="nav-item active">
          <a class="nav-link" href="{% url 'users:register' %}">Kayıt Ol</a>
      </li>
      {% endif %}
    </ul>
    <form action="{% url 'meow:search' %}" class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Ara" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Ara</button>
    </form>
  </div>
</nav>

templates/partials/sidebar.html
{% load thumbnail %}

<div class="col-md-3 sidebar">
    <div class="jumbotron">
            {% with user.profile as profile %}
        <div class="media">
            {% thumbnail profile.avatar "64x64" format="PNG" as im %}
                <img src="{{ im.url }}" class="align-self-center mr-3" alt="...">
            {% endthumbnail %}
            <div class="media-body">
                <h5 class="">
                    <a href="/u/{{ user.get_username }}">
                        {{ user.get_username }}
                    </a>
                </h5>
            </div>
        </div>
        <p>
            {{ profile.bio }}
        </p>
        <hr>
            {% endwith %}
        {% if user.is_authenticated %}
        <form action="{% url 'meow:create'%}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_body">Meowınız:</label>
                <textarea class="form-control" name="body" rows="3" maxlength="512" required="" id="id_body"></textarea>
            </div>
            <div class="form-group">
                <label for="id_image">Görsel <small>(isteğe bağlı)</small>:</label>
                <input type="file" name="image" accept="image/*" id="id_image">
            </div>
            <button type="submit" class="btn btn-success">Meowla</button>
        </form>
        <hr>
        {% endif %}
    </div>
</div>

templates/user.html
{% extends "base.html" %}

{% load thumbnail %}

{% block body %}
<div class="media user-info">
    {% thumbnail user.profile.avatar "128x128" format="PNG" as im %}
        <img src="{{ im.url }}" class="align-self-center mr-3" alt="...">
    {% endthumbnail %}
    <div class="media-body">
        <h5 class="mt-0">{{ user.get_username }}</h5>
        <p>{{ user.profile.bio }}</p>
    </div>
</div>
<div class="container profile_meows">
	{% for meow in user.meow_set.all %}
        {% include  "partials/meow.html" with meow=meow %}
	{% endfor %}
</div>
{% endblock body %}

templates/user_form.html
{% extends "base.html" %}

{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if profile_form %}
        {{ profile_form.as_p }}
    {% endif %}
    <button type="submit">{{ button }}</button>
</form>
{% endblock body %}